### ISSUE TITLE
Invalid type for postgres enum

### ISSUE THREAD

**Issue by Sicria** [nene/prettier-plugin-sql-cst#29] opened 2024-06-16 10:01 UTC
Using the following snippet in the playground causes an error. 

I know it's mentioned as experimental but it would be great if additional support was added or if there was a way to disable certain blocks/lines.

https://nene.github.io/prettier-sql-playground/
```
create type public.preference_type as ENUM (
  'table_columns_list',
  'table_columns_page'
);
```

**Comment by nene** [comment] 2024-06-18 08:48
Yes, Postgres support is far from complete. But thanks for reporting, this helps me to prioritize the features these missing features that people actually use the most.

You can follow the progress of implementing Postgres parser in [sql-parser-cst repository](https://github.com/nene/sql-parser-cst/issues/40). There's also a separate task for the [CREATE TYPE](https://github.com/nene/sql-parser-cst/issues/78) syntax support.

I'll close this issue, here as the problem is on the parser side, not in the prettier plugin.

**Closed by nene** 2024-06-18 08:48 UTC
